name : face3d
dependencies :
  - python=3.6
  - pip
  - tensorflow-gpu == 1.12.0
  - keras==2.2.4
  - pip :
      - mtcnn
      - pillow
      - argparse
      - scipy
      - scikit-image
      - torch==1.5.1 #pip uninstall tensorboard
      - torchvision==0.6.1
      - imgaug
      - opencv-python
      - dlib
      - tqdm